"""
product_catalog.py – Built-in synthetic demo product catalog.
All data is clearly marked as demo/synthetic.
"""
from typing import List, Dict, Any, Optional


DEMO_LAPTOPS: List[Dict[str, Any]] = [
    {
        "id": "lap001",
        "name": "Lenovo IdeaPad Slim 3 (AMD Ryzen 5)",
        "category": "laptop",
        "price": "₹45,990 (est.)",
        "price_num": 45990,
        "rating": 4.1,
        "specs": {
            "processor": "AMD Ryzen 5 5500U",
            "ram": "8GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD",
            "battery": "8–10 hrs",
            "weight": "1.65 kg",
            "os": "Windows 11",
            "gpu": "Integrated Radeon",
        },
        "tags": ["budget", "student", "everyday", "programming"],
        "performance_tier": 2,
        "portability": 3,
        "battery_score": 4,
        "gaming": 1,
        "ai_ml": 1,
        "demo_data": True,
    },
    {
        "id": "lap002",
        "name": "ASUS VivoBook 15 (Intel i5 12th Gen)",
        "category": "laptop",
        "price": "₹55,990 (est.)",
        "price_num": 55990,
        "rating": 4.2,
        "specs": {
            "processor": "Intel Core i5-1235U",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD",
            "battery": "7–9 hrs",
            "weight": "1.8 kg",
            "os": "Windows 11",
            "gpu": "Intel Iris Xe",
        },
        "tags": ["mid-range", "student", "programming", "office"],
        "performance_tier": 3,
        "portability": 3,
        "battery_score": 3,
        "gaming": 1,
        "ai_ml": 2,
        "demo_data": True,
    },
    {
        "id": "lap003",
        "name": "HP Pavilion Gaming 15 (RTX 3050)",
        "category": "laptop",
        "price": "₹72,990 (est.)",
        "price_num": 72990,
        "rating": 4.3,
        "specs": {
            "processor": "Intel Core i5-12450H",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD 144Hz",
            "battery": "5–7 hrs",
            "weight": "2.2 kg",
            "os": "Windows 11",
            "gpu": "NVIDIA RTX 3050 4GB",
        },
        "tags": ["gaming", "mid-range", "programming"],
        "performance_tier": 4,
        "portability": 2,
        "battery_score": 2,
        "gaming": 4,
        "ai_ml": 3,
        "demo_data": True,
    },
    {
        "id": "lap004",
        "name": "Dell XPS 13 (Intel i7 12th Gen)",
        "category": "laptop",
        "price": "₹1,10,990 (est.)",
        "price_num": 110990,
        "rating": 4.5,
        "specs": {
            "processor": "Intel Core i7-1250U",
            "ram": "16GB LPDDR5",
            "storage": "512GB SSD",
            "display": "13.4\" FHD+",
            "battery": "10–12 hrs",
            "weight": "1.27 kg",
            "os": "Windows 11",
            "gpu": "Intel Iris Xe",
        },
        "tags": ["ultrabook", "professional", "portable", "premium"],
        "performance_tier": 4,
        "portability": 5,
        "battery_score": 5,
        "gaming": 1,
        "ai_ml": 2,
        "demo_data": True,
    },
    {
        "id": "lap005",
        "name": "ASUS ROG Strix G15 (RTX 4060)",
        "category": "laptop",
        "price": "₹1,25,990 (est.)",
        "price_num": 125990,
        "rating": 4.6,
        "specs": {
            "processor": "AMD Ryzen 7 6800H",
            "ram": "16GB DDR5",
            "storage": "1TB SSD",
            "display": "15.6\" QHD 165Hz",
            "battery": "4–6 hrs",
            "weight": "2.4 kg",
            "os": "Windows 11",
            "gpu": "NVIDIA RTX 4060 8GB",
        },
        "tags": ["gaming", "high-performance", "ai_ml"],
        "performance_tier": 5,
        "portability": 1,
        "battery_score": 1,
        "gaming": 5,
        "ai_ml": 4,
        "demo_data": True,
    },
    {
        "id": "lap006",
        "name": "Acer Aspire 5 (AMD Ryzen 3)",
        "category": "laptop",
        "price": "₹32,990 (est.)",
        "price_num": 32990,
        "rating": 3.9,
        "specs": {
            "processor": "AMD Ryzen 3 5300U",
            "ram": "8GB DDR4",
            "storage": "256GB SSD",
            "display": "15.6\" FHD",
            "battery": "8 hrs",
            "weight": "1.9 kg",
            "os": "Windows 11 S",
            "gpu": "Integrated",
        },
        "tags": ["ultra-budget", "basic", "student"],
        "performance_tier": 1,
        "portability": 3,
        "battery_score": 4,
        "gaming": 0,
        "ai_ml": 0,
        "demo_data": True,
    },
    {
        "id": "lap007",
        "name": "MacBook Air M2",
        "category": "laptop",
        "price": "₹1,14,990 (est.)",
        "price_num": 114990,
        "rating": 4.8,
        "specs": {
            "processor": "Apple M2 8-core",
            "ram": "8GB Unified",
            "storage": "256GB SSD",
            "display": "13.6\" Liquid Retina",
            "battery": "15–18 hrs",
            "weight": "1.24 kg",
            "os": "macOS",
            "gpu": "8-core GPU",
        },
        "tags": ["ultrabook", "premium", "portable", "professional"],
        "performance_tier": 4,
        "portability": 5,
        "battery_score": 5,
        "gaming": 1,
        "ai_ml": 3,
        "demo_data": True,
    },
    {
        "id": "lap008",
        "name": "HP Victus 15 (RTX 3050 Ti)",
        "category": "laptop",
        "price": "₹65,990 (est.)",
        "price_num": 65990,
        "rating": 4.2,
        "specs": {
            "processor": "Intel Core i5-12450H",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD 144Hz",
            "battery": "5–7 hrs",
            "weight": "2.3 kg",
            "os": "Windows 11",
            "gpu": "NVIDIA RTX 3050 Ti 4GB",
        },
        "tags": ["gaming", "mid-range", "value"],
        "performance_tier": 3,
        "portability": 2,
        "battery_score": 2,
        "gaming": 3,
        "ai_ml": 2,
        "demo_data": True,
    },
]

DEMO_PHONES: List[Dict[str, Any]] = [
    {
        "id": "ph001",
        "name": "Samsung Galaxy M34 5G",
        "category": "smartphone",
        "price": "₹18,999 (est.)",
        "price_num": 18999,
        "rating": 4.2,
        "specs": {
            "processor": "Exynos 1280",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.5\" Super AMOLED 120Hz",
            "battery": "6000 mAh",
            "camera": "50MP triple",
            "os": "Android 13",
        },
        "tags": ["budget", "5G", "battery", "student"],
        "demo_data": True,
    },
    {
        "id": "ph002",
        "name": "OnePlus Nord CE3 Lite 5G",
        "category": "smartphone",
        "price": "₹19,999 (est.)",
        "price_num": 19999,
        "rating": 4.1,
        "specs": {
            "processor": "Snapdragon 695",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.72\" LCD 120Hz",
            "battery": "5000 mAh 67W",
            "camera": "108MP",
            "os": "Android 13",
        },
        "tags": ["budget", "5G", "fast-charge"],
        "demo_data": True,
    },
    {
        "id": "ph003",
        "name": "Samsung Galaxy S23 FE",
        "category": "smartphone",
        "price": "₹49,999 (est.)",
        "price_num": 49999,
        "rating": 4.4,
        "specs": {
            "processor": "Exynos 2200",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.4\" Dynamic AMOLED 120Hz",
            "battery": "4500 mAh 25W",
            "camera": "50MP triple OIS",
            "os": "Android 13",
        },
        "tags": ["mid-range", "camera", "premium-feel"],
        "demo_data": True,
    },
    {
        "id": "ph004",
        "name": "Apple iPhone 15",
        "category": "smartphone",
        "price": "₹79,999 (est.)",
        "price_num": 79999,
        "rating": 4.7,
        "specs": {
            "processor": "A16 Bionic",
            "ram": "6GB",
            "storage": "128GB",
            "display": "6.1\" Super Retina XDR",
            "battery": "3227 mAh",
            "camera": "48MP dual OIS",
            "os": "iOS 17",
        },
        "tags": ["premium", "ios", "camera", "performance"],
        "demo_data": True,
    },
    {
        "id": "ph005",
        "name": "Redmi Note 13 Pro+ 5G",
        "category": "smartphone",
        "price": "₹29,999 (est.)",
        "price_num": 29999,
        "rating": 4.3,
        "specs": {
            "processor": "Dimensity 7200 Ultra",
            "ram": "12GB",
            "storage": "256GB",
            "display": "6.67\" AMOLED 120Hz",
            "battery": "5000 mAh 120W",
            "camera": "200MP OIS",
            "os": "Android 13",
        },
        "tags": ["mid-range", "camera", "fast-charge", "5G"],
        "demo_data": True,
    },
    {
        "id": "ph006",
        "name": "OnePlus 12R",
        "category": "smartphone",
        "price": "₹39,999 (est.)",
        "price_num": 39999,
        "rating": 4.4,
        "specs": {
            "processor": "Snapdragon 8 Gen 1",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.78\" AMOLED 120Hz",
            "battery": "5500 mAh 80W",
            "camera": "50MP triple",
            "os": "Android 14",
        },
        "tags": ["performance", "value", "gaming-phone"],
        "demo_data": True,
    },
]

DEMO_OFFICE_EQUIPMENT: List[Dict[str, Any]] = [
    {
        "id": "oe001",
        "name": "HP LaserJet Pro M404n Printer",
        "category": "office_equipment",
        "price": "₹18,500 (est.)",
        "price_num": 18500,
        "rating": 4.3,
        "specs": {
            "type": "Monochrome Laser",
            "speed": "38 ppm",
            "connectivity": "Ethernet, USB",
            "duty_cycle": "Up to 80,000 pages/month",
        },
        "tags": ["printer", "laser", "office", "fast"],
        "demo_data": True,
    },
    {
        "id": "oe002",
        "name": "Dell 27\" Monitor P2723D (QHD)",
        "category": "office_equipment",
        "price": "₹28,990 (est.)",
        "price_num": 28990,
        "rating": 4.5,
        "specs": {
            "display": "27\" IPS QHD 2560x1440",
            "refresh_rate": "60Hz",
            "ports": "HDMI, DisplayPort, USB-C",
            "vesa": "Yes",
        },
        "tags": ["monitor", "office", "productivity"],
        "demo_data": True,
    },
    {
        "id": "oe003",
        "name": "Logitech MX Keys Wireless Keyboard",
        "category": "office_equipment",
        "price": "₹9,495 (est.)",
        "price_num": 9495,
        "rating": 4.6,
        "specs": {
            "connectivity": "Bluetooth, Unifying USB",
            "battery": "Up to 10 days",
            "backlight": "Adaptive",
            "layout": "Full size",
        },
        "tags": ["keyboard", "wireless", "productivity"],
        "demo_data": True,
    },
    {
        "id": "oe004",
        "name": "Herman Miller Aeron Chair",
        "category": "office_equipment",
        "price": "₹1,20,000 (est.)",
        "price_num": 120000,
        "rating": 4.8,
        "specs": {
            "type": "Ergonomic Office Chair",
            "adjustment": "Full lumbar, seat, arm",
            "warranty": "12 years",
        },
        "tags": ["chair", "ergonomic", "premium"],
        "demo_data": True,
    },
    {
        "id": "oe005",
        "name": "Brother MFC-L2750DW Multifunction Printer",
        "category": "office_equipment",
        "price": "₹22,000 (est.)",
        "price_num": 22000,
        "rating": 4.2,
        "specs": {
            "type": "Monochrome Laser MFC",
            "functions": "Print, Scan, Copy, Fax",
            "connectivity": "Wi-Fi, Ethernet, USB",
        },
        "tags": ["printer", "multifunction", "wireless", "office"],
        "demo_data": True,
    },
]

DEMO_FISH_AQUARIUM: List[Dict[str, Any]] = [
    {
        "id": "aq001",
        "name": "Betta Splendens (Siamese Fighting Fish)",
        "category": "fish_aquarium",
        "price": "₹100–₹500 (est.)",
        "price_num": 200,
        "rating": 4.5,
        "specs": {
            "tank_size": "Minimum 10 litres",
            "water_type": "Freshwater",
            "difficulty": "Beginner",
            "temperament": "Solitary",
            "lifespan": "3–5 years",
            "diet": "Pellets, frozen/live food",
        },
        "tags": ["freshwater", "beginner", "solitary", "colorful"],
        "demo_data": True,
    },
    {
        "id": "aq002",
        "name": "Neon Tetra",
        "category": "fish_aquarium",
        "price": "₹50–₹80 per fish (est.)",
        "price_num": 65,
        "rating": 4.6,
        "specs": {
            "tank_size": "Minimum 40 litres",
            "water_type": "Freshwater",
            "difficulty": "Beginner–Intermediate",
            "temperament": "Peaceful schooling",
            "lifespan": "5–10 years",
            "diet": "Micro pellets, flakes",
        },
        "tags": ["freshwater", "beginner", "schooling", "colorful"],
        "demo_data": True,
    },
    {
        "id": "aq003",
        "name": "Goldfish (Common / Fancy)",
        "category": "fish_aquarium",
        "price": "₹50–₹500 per fish (est.)",
        "price_num": 150,
        "rating": 4.2,
        "specs": {
            "tank_size": "Minimum 75 litres",
            "water_type": "Freshwater",
            "difficulty": "Beginner",
            "temperament": "Peaceful",
            "lifespan": "10–15 years",
            "diet": "Pellets, vegetables",
        },
        "tags": ["freshwater", "beginner", "popular"],
        "demo_data": True,
    },
    {
        "id": "aq004",
        "name": "Clownfish (Amphiprioninae)",
        "category": "fish_aquarium",
        "price": "₹500–₹2000 (est.)",
        "price_num": 1000,
        "rating": 4.7,
        "specs": {
            "tank_size": "Minimum 75 litres",
            "water_type": "Saltwater",
            "difficulty": "Intermediate",
            "temperament": "Semi-aggressive",
            "lifespan": "6–10 years",
            "diet": "Omnivore – pellets, frozen food",
        },
        "tags": ["saltwater", "intermediate", "colorful", "popular"],
        "demo_data": True,
    },
    {
        "id": "aq005",
        "name": "Aqueon 20 Gallon Aquarium Starter Kit",
        "category": "fish_aquarium",
        "price": "₹8,000–₹12,000 (est.)",
        "price_num": 10000,
        "rating": 4.1,
        "specs": {
            "volume": "75 litres (20 gallons)",
            "includes": "Filter, LED light, heater, hood",
            "type": "Glass",
            "suitable_for": "Freshwater beginners",
        },
        "tags": ["tank", "starter-kit", "freshwater", "beginner"],
        "demo_data": True,
    },
    {
        "id": "aq006",
        "name": "API Master Test Kit (Freshwater)",
        "category": "fish_aquarium",
        "price": "₹2,500–₹3,500 (est.)",
        "price_num": 3000,
        "rating": 4.8,
        "specs": {
            "tests": "pH, Ammonia, Nitrite, Nitrate",
            "tests_per_kit": "800+",
            "type": "Liquid reagent test",
        },
        "tags": ["water-testing", "maintenance", "essential"],
        "demo_data": True,
    },
]

DEMO_PET_SUPPLIES: List[Dict[str, Any]] = [
    {
        "id": "pet001",
        "name": "Royal Canin Maxi Adult Dog Food (4kg)",
        "category": "pet",
        "price": "₹2,200 (est.)",
        "price_num": 2200,
        "rating": 4.5,
        "specs": {
            "type": "Dry Dog Food",
            "weight": "4 kg",
            "breed_size": "Large breeds (26–44 kg)",
            "ingredients": "Chicken meal, rice, corn",
        },
        "tags": ["dog", "food", "large-breed", "dry"],
        "demo_data": True,
    },
    {
        "id": "pet002",
        "name": "Whiskas Tuna Pouch Cat Food (85g x 12)",
        "category": "pet",
        "price": "₹650 (est.)",
        "price_num": 650,
        "rating": 4.3,
        "specs": {
            "type": "Wet Cat Food",
            "weight": "12 x 85g",
            "flavour": "Tuna in Jelly",
        },
        "tags": ["cat", "food", "wet"],
        "demo_data": True,
    },
    {
        "id": "pet003",
        "name": "Pet Zone Dog Carrier Bag (Medium)",
        "category": "pet",
        "price": "₹1,800 (est.)",
        "price_num": 1800,
        "rating": 4.0,
        "specs": {
            "dimensions": "45 x 30 x 28 cm",
            "material": "Oxford fabric",
            "capacity": "Up to 6 kg pet",
            "features": "Mesh windows, shoulder strap",
        },
        "tags": ["dog", "cat", "carrier", "travel"],
        "demo_data": True,
    },
    {
        "id": "pet004",
        "name": "Pedigree Adult Dog Food Chicken & Vegetables (3kg)",
        "category": "pet",
        "price": "₹750 (est.)",
        "price_num": 750,
        "rating": 4.1,
        "specs": {
            "type": "Dry Dog Food",
            "weight": "3 kg",
            "flavour": "Chicken & Vegetables",
        },
        "tags": ["dog", "food", "budget", "dry"],
        "demo_data": True,
    },
    {
        "id": "pet005",
        "name": "Trixie Scratching Post for Cats (60cm)",
        "category": "pet",
        "price": "₹1,200 (est.)",
        "price_num": 1200,
        "rating": 4.2,
        "specs": {
            "height": "60 cm",
            "material": "Sisal, plush",
            "base": "Weighted",
        },
        "tags": ["cat", "scratching", "toy", "furniture"],
        "demo_data": True,
    },
]

DEMO_RELATIONSHIP_RESOURCES: List[Dict[str, Any]] = [
    {
        "id": "rel001",
        "name": "Nonviolent Communication: A Language of Life (Marshall Rosenberg)",
        "category": "relationship",
        "price": "₹499 (est. paperback)",
        "price_num": 499,
        "rating": 4.8,
        "specs": {
            "type": "Communication Guide",
            "topic": "Conflict Resolution & Empathy",
            "format": "Paperback / Audiobook",
            "recommended_for": "Healing strained relationships",
        },
        "tags": ["communication", "conflict-resolution", "empathy", "relationships"],
        "demo_data": True,
    },
    {
        "id": "rel002",
        "name": "Difficult Conversations: How to Discuss What Matters Most",
        "category": "relationship",
        "price": "₹450 (est. paperback)",
        "price_num": 450,
        "rating": 4.7,
        "specs": {
            "type": "Handbook",
            "topic": "Harvard Negotiation Project Framework",
            "format": "Book",
            "recommended_for": "Navigating intense disagreements",
        },
        "tags": ["conversations", "friendship", "boundaries"],
        "demo_data": True,
    },
    {
        "id": "rel003",
        "name": "Attached: The New Science of Adult Attachment",
        "category": "relationship",
        "price": "₹399 (est. paperback)",
        "price_num": 399,
        "rating": 4.6,
        "specs": {
            "type": "Psychology Guide",
            "topic": "Attachment Styles & Dependency",
            "format": "Book",
            "recommended_for": "Understanding fear of abandonment and healthy boundaries",
        },
        "tags": ["attachment", "emotional-independence", "relationships"],
        "demo_data": True,
    },
]

ALL_PRODUCTS = DEMO_LAPTOPS + DEMO_PHONES + DEMO_OFFICE_EQUIPMENT + DEMO_FISH_AQUARIUM + DEMO_PET_SUPPLIES + DEMO_RELATIONSHIP_RESOURCES

CATEGORY_PRODUCT_MAP = {
    "laptop": DEMO_LAPTOPS,
    "smartphone": DEMO_PHONES,
    "phone": DEMO_PHONES,
    "office_equipment": DEMO_OFFICE_EQUIPMENT,
    "fish_aquarium": DEMO_FISH_AQUARIUM,
    "pet": DEMO_PET_SUPPLIES,
    "company_bulk": DEMO_LAPTOPS + DEMO_OFFICE_EQUIPMENT,
    "relationship": DEMO_RELATIONSHIP_RESOURCES,
    "personal": DEMO_RELATIONSHIP_RESOURCES,
    "product_purchase": ALL_PRODUCTS,
}


def get_products_for_category(category: str, budget: Optional[float] = None, quantity: int = 1) -> List[Dict[str, Any]]:
    """Return filtered demo products for a category."""
    category = category.lower().strip()
    products = CATEGORY_PRODUCT_MAP.get(category, [])
    if not products:
        # Try partial match
        for key, prods in CATEGORY_PRODUCT_MAP.items():
            if key in category or category in key:
                products = prods
                break

    if budget and products:
        unit_budget = budget / max(quantity, 1)
        products = [p for p in products if p.get("price_num", 0) <= unit_budget * 1.2]

    return products
