"""
product_catalog.py – Built-in synthetic demo product catalog.
All data is clearly marked as demo/synthetic.
"""
from typing import List, Dict, Any, Optional


DEMO_LAPTOPS: List[Dict[str, Any]] = [
    {
        "id": "lap001",
        "name": "Lenovo IdeaPad Slim 3 (AMD Ryzen 5)",
        "category": "laptop",
        "price": "₹45,990 (est.)",
        "price_num": 45990,
        "rating": 4.1,
        "specs": {
            "processor": "AMD Ryzen 5 5500U",
            "ram": "8GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD",
            "battery": "8–10 hrs",
            "weight": "1.65 kg",
            "os": "Windows 11",
            "gpu": "Integrated Radeon",
        },
        "tags": ["budget", "student", "everyday", "programming"],
        "performance_tier": 2,
        "portability": 3,
        "battery_score": 4,
        "gaming": 1,
        "ai_ml": 1,
        "demo_data": True,
    },
    {
        "id": "lap002",
        "name": "ASUS VivoBook 15 (Intel i5 12th Gen)",
        "category": "laptop",
        "price": "₹55,990 (est.)",
        "price_num": 55990,
        "rating": 4.2,
        "specs": {
            "processor": "Intel Core i5-1235U",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD",
            "battery": "7–9 hrs",
            "weight": "1.8 kg",
            "os": "Windows 11",
            "gpu": "Intel Iris Xe",
        },
        "tags": ["mid-range", "student", "programming", "office"],
        "performance_tier": 3,
        "portability": 3,
        "battery_score": 3,
        "gaming": 1,
        "ai_ml": 2,
        "demo_data": True,
    },
    {
        "id": "lap003",
        "name": "HP Pavilion Gaming 15 (RTX 3050)",
        "category": "laptop",
        "price": "₹72,990 (est.)",
        "price_num": 72990,
        "rating": 4.3,
        "specs": {
            "processor": "Intel Core i5-12450H",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD 144Hz",
            "battery": "5–7 hrs",
            "weight": "2.2 kg",
            "os": "Windows 11",
            "gpu": "NVIDIA RTX 3050 4GB",
        },
        "tags": ["gaming", "mid-range", "programming"],
        "performance_tier": 4,
        "portability": 2,
        "battery_score": 2,
        "gaming": 4,
        "ai_ml": 3,
        "demo_data": True,
    },
    {
        "id": "lap004",
        "name": "Dell XPS 13 (Intel i7 12th Gen)",
        "category": "laptop",
        "price": "₹1,10,990 (est.)",
        "price_num": 110990,
        "rating": 4.5,
        "specs": {
            "processor": "Intel Core i7-1250U",
            "ram": "16GB LPDDR5",
            "storage": "512GB SSD",
            "display": "13.4\" FHD+",
            "battery": "10–12 hrs",
            "weight": "1.27 kg",
            "os": "Windows 11",
            "gpu": "Intel Iris Xe",
        },
        "tags": ["ultrabook", "professional", "portable", "premium"],
        "performance_tier": 4,
        "portability": 5,
        "battery_score": 5,
        "gaming": 1,
        "ai_ml": 2,
        "demo_data": True,
    },
    {
        "id": "lap005",
        "name": "ASUS ROG Strix G15 (RTX 4060)",
        "category": "laptop",
        "price": "₹1,25,990 (est.)",
        "price_num": 125990,
        "rating": 4.6,
        "specs": {
            "processor": "AMD Ryzen 7 6800H",
            "ram": "16GB DDR5",
            "storage": "1TB SSD",
            "display": "15.6\" QHD 165Hz",
            "battery": "4–6 hrs",
            "weight": "2.4 kg",
            "os": "Windows 11",
            "gpu": "NVIDIA RTX 4060 8GB",
        },
        "tags": ["gaming", "high-performance", "ai_ml"],
        "performance_tier": 5,
        "portability": 1,
        "battery_score": 1,
        "gaming": 5,
        "ai_ml": 4,
        "demo_data": True,
    },
    {
        "id": "lap006",
        "name": "Acer Aspire 5 (AMD Ryzen 3)",
        "category": "laptop",
        "price": "₹32,990 (est.)",
        "price_num": 32990,
        "rating": 3.9,
        "specs": {
            "processor": "AMD Ryzen 3 5300U",
            "ram": "8GB DDR4",
            "storage": "256GB SSD",
            "display": "15.6\" FHD",
            "battery": "8 hrs",
            "weight": "1.9 kg",
            "os": "Windows 11 S",
            "gpu": "Integrated",
        },
        "tags": ["ultra-budget", "basic", "student"],
        "performance_tier": 1,
        "portability": 3,
        "battery_score": 4,
        "gaming": 0,
        "ai_ml": 0,
        "demo_data": True,
    },
    {
        "id": "lap007",
        "name": "MacBook Air M2",
        "category": "laptop",
        "price": "₹1,14,990 (est.)",
        "price_num": 114990,
        "rating": 4.8,
        "specs": {
            "processor": "Apple M2 8-core",
            "ram": "8GB Unified",
            "storage": "256GB SSD",
            "display": "13.6\" Liquid Retina",
            "battery": "15–18 hrs",
            "weight": "1.24 kg",
            "os": "macOS",
            "gpu": "8-core GPU",
        },
        "tags": ["ultrabook", "premium", "portable", "professional"],
        "performance_tier": 4,
        "portability": 5,
        "battery_score": 5,
        "gaming": 1,
        "ai_ml": 3,
        "demo_data": True,
    },
    {
        "id": "lap008",
        "name": "HP Victus 15 (RTX 3050 Ti)",
        "category": "laptop",
        "price": "₹65,990 (est.)",
        "price_num": 65990,
        "rating": 4.2,
        "specs": {
            "processor": "Intel Core i5-12450H",
            "ram": "16GB DDR4",
            "storage": "512GB SSD",
            "display": "15.6\" FHD 144Hz",
            "battery": "5–7 hrs",
            "weight": "2.3 kg",
            "os": "Windows 11",
            "gpu": "NVIDIA RTX 3050 Ti 4GB",
        },
        "tags": ["gaming", "mid-range", "value"],
        "performance_tier": 3,
        "portability": 2,
        "battery_score": 2,
        "gaming": 3,
        "ai_ml": 2,
        "demo_data": True,
    },
]

DEMO_PHONES: List[Dict[str, Any]] = [
    {
        "id": "ph001",
        "name": "Samsung Galaxy M34 5G",
        "category": "smartphone",
        "price": "₹18,999 (est.)",
        "price_num": 18999,
        "rating": 4.2,
        "specs": {
            "processor": "Exynos 1280",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.5\" Super AMOLED 120Hz",
            "battery": "6000 mAh",
            "camera": "50MP triple",
            "os": "Android 13",
        },
        "tags": ["budget", "5G", "battery", "student"],
        "demo_data": True,
    },
    {
        "id": "ph002",
        "name": "OnePlus Nord CE3 Lite 5G",
        "category": "smartphone",
        "price": "₹19,999 (est.)",
        "price_num": 19999,
        "rating": 4.1,
        "specs": {
            "processor": "Snapdragon 695",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.72\" LCD 120Hz",
            "battery": "5000 mAh 67W",
            "camera": "108MP",
            "os": "Android 13",
        },
        "tags": ["budget", "5G", "fast-charge"],
        "demo_data": True,
    },
    {
        "id": "ph_iphone13",
        "name": "Apple iPhone 13 (128GB)",
        "category": "smartphone",
        "price": "₹48,999 (est.)",
        "price_num": 48999,
        "rating": 4.7,
        "specs": {
            "processor": "A15 Bionic (4-core GPU)",
            "ram": "4GB",
            "storage": "128GB",
            "display": "6.1\" Super Retina XDR OLED",
            "battery": "3227 mAh (all-day)",
            "camera": "12MP Dual with Sensor-shift OIS",
            "os": "iOS 17",
        },
        "tags": ["ios", "apple", "camera", "mid-range", "premium-feel", "iphone 13"],
        "demo_data": True,
    },
    {
        "id": "ph_iphone14",
        "name": "Apple iPhone 14 (128GB)",
        "category": "smartphone",
        "price": "₹58,990 (est.)",
        "price_num": 58990,
        "rating": 4.6,
        "specs": {
            "processor": "A15 Bionic (5-core GPU)",
            "ram": "6GB",
            "storage": "128GB",
            "display": "6.1\" Super Retina XDR OLED",
            "battery": "3279 mAh",
            "camera": "12MP Dual with Photonic Engine",
            "os": "iOS 17",
        },
        "tags": ["ios", "apple", "camera", "premium", "iphone 14"],
        "demo_data": True,
    },
    {
        "id": "ph_apple_adapter",
        "name": "Apple 20W USB-C Power Adapter",
        "category": "smartphone",
        "price": "₹1,900 (est.)",
        "price_num": 1900,
        "rating": 4.8,
        "specs": {
            "type": "Fast Wall Charger",
            "wattage": "20W USB-C",
            "compatibility": "iPhone 12, 13, 14, 15 series, iPad",
            "safety": "Over-voltage and short-circuit protection",
        },
        "tags": ["ios", "apple", "accessory", "charger", "iphone 13", "iphone 14"],
        "demo_data": True,
    },
    {
        "id": "ph_iphone13_case",
        "name": "Spigen Ultra Hybrid Case for iPhone 13",
        "category": "smartphone",
        "price": "₹1,299 (est.)",
        "price_num": 1299,
        "rating": 4.7,
        "specs": {
            "protection": "Air Cushion Drop Protection (Mil-Grade)",
            "material": "TPU Bumper + Polycarbonate Back",
            "finish": "Crystal Clear (Non-yellowing)",
        },
        "tags": ["ios", "apple", "accessory", "case", "iphone 13"],
        "demo_data": True,
    },
    {
        "id": "ph_pixel7a",
        "name": "Google Pixel 7a 5G",
        "category": "smartphone",
        "price": "₹37,999 (est.)",
        "price_num": 37999,
        "rating": 4.4,
        "specs": {
            "processor": "Google Tensor G2",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.1\" OLED 90Hz",
            "battery": "4385 mAh 18W",
            "camera": "64MP OIS + 13MP Ultra-wide",
            "os": "Stock Android 14",
        },
        "tags": ["android", "camera", "clean-ui", "google", "pixel"],
        "demo_data": True,
    },
    {
        "id": "ph003",
        "name": "Samsung Galaxy S23 FE",
        "category": "smartphone",
        "price": "₹49,999 (est.)",
        "price_num": 49999,
        "rating": 4.4,
        "specs": {
            "processor": "Exynos 2200",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.4\" Dynamic AMOLED 120Hz",
            "battery": "4500 mAh 25W",
            "camera": "50MP triple OIS",
            "os": "Android 13",
        },
        "tags": ["mid-range", "camera", "premium-feel"],
        "demo_data": True,
    },
    {
        "id": "ph004",
        "name": "Apple iPhone 15",
        "category": "smartphone",
        "price": "₹79,999 (est.)",
        "price_num": 79999,
        "rating": 4.7,
        "specs": {
            "processor": "A16 Bionic",
            "ram": "6GB",
            "storage": "128GB",
            "display": "6.1\" Super Retina XDR",
            "battery": "3227 mAh",
            "camera": "48MP dual OIS",
            "os": "iOS 17",
        },
        "tags": ["premium", "ios", "camera", "performance"],
        "demo_data": True,
    },
    {
        "id": "ph005",
        "name": "Redmi Note 13 Pro+ 5G",
        "category": "smartphone",
        "price": "₹29,999 (est.)",
        "price_num": 29999,
        "rating": 4.3,
        "specs": {
            "processor": "Dimensity 7200 Ultra",
            "ram": "12GB",
            "storage": "256GB",
            "display": "6.67\" AMOLED 120Hz",
            "battery": "5000 mAh 120W",
            "camera": "200MP OIS",
            "os": "Android 13",
        },
        "tags": ["mid-range", "camera", "fast-charge", "5G"],
        "demo_data": True,
    },
    {
        "id": "ph006",
        "name": "OnePlus 12R",
        "category": "smartphone",
        "price": "₹39,999 (est.)",
        "price_num": 39999,
        "rating": 4.4,
        "specs": {
            "processor": "Snapdragon 8 Gen 1",
            "ram": "8GB",
            "storage": "128GB",
            "display": "6.78\" AMOLED 120Hz",
            "battery": "5500 mAh 80W",
            "camera": "50MP triple",
            "os": "Android 14",
        },
        "tags": ["performance", "value", "gaming-phone"],
        "demo_data": True,
    },
]

DEMO_OFFICE_EQUIPMENT: List[Dict[str, Any]] = [
    {
        "id": "oe001",
        "name": "HP LaserJet Pro M404n Printer",
        "category": "office_equipment",
        "price": "₹18,500 (est.)",
        "price_num": 18500,
        "rating": 4.3,
        "specs": {
            "type": "Monochrome Laser",
            "speed": "38 ppm",
            "connectivity": "Ethernet, USB",
            "duty_cycle": "Up to 80,000 pages/month",
        },
        "tags": ["printer", "laser", "office", "fast"],
        "demo_data": True,
    },
    {
        "id": "oe002",
        "name": "Dell 27\" Monitor P2723D (QHD)",
        "category": "office_equipment",
        "price": "₹28,990 (est.)",
        "price_num": 28990,
        "rating": 4.5,
        "specs": {
            "display": "27\" IPS QHD 2560x1440",
            "refresh_rate": "60Hz",
            "ports": "HDMI, DisplayPort, USB-C",
            "vesa": "Yes",
        },
        "tags": ["monitor", "office", "productivity"],
        "demo_data": True,
    },
    {
        "id": "oe003",
        "name": "Logitech MX Keys Wireless Keyboard",
        "category": "office_equipment",
        "price": "₹9,495 (est.)",
        "price_num": 9495,
        "rating": 4.6,
        "specs": {
            "connectivity": "Bluetooth, Unifying USB",
            "battery": "Up to 10 days",
            "backlight": "Adaptive",
            "layout": "Full size",
        },
        "tags": ["keyboard", "wireless", "productivity"],
        "demo_data": True,
    },
    {
        "id": "oe004",
        "name": "Herman Miller Aeron Chair",
        "category": "office_equipment",
        "price": "₹1,20,000 (est.)",
        "price_num": 120000,
        "rating": 4.8,
        "specs": {
            "type": "Ergonomic Office Chair",
            "adjustment": "Full lumbar, seat, arm",
            "warranty": "12 years",
        },
        "tags": ["chair", "ergonomic", "premium"],
        "demo_data": True,
    },
    {
        "id": "oe005",
        "name": "Brother MFC-L2750DW Multifunction Printer",
        "category": "office_equipment",
        "price": "₹22,000 (est.)",
        "price_num": 22000,
        "rating": 4.2,
        "specs": {
            "type": "Monochrome Laser MFC",
            "functions": "Print, Scan, Copy, Fax",
            "connectivity": "Wi-Fi, Ethernet, USB",
        },
        "tags": ["printer", "multifunction", "wireless", "office"],
        "demo_data": True,
    },
]

DEMO_FISH_AQUARIUM: List[Dict[str, Any]] = [
    {
        "id": "aq001",
        "name": "Betta Splendens (Siamese Fighting Fish)",
        "category": "fish_aquarium",
        "price": "₹100–₹500 (est.)",
        "price_num": 200,
        "rating": 4.5,
        "specs": {
            "tank_size": "Minimum 10 litres",
            "water_type": "Freshwater",
            "difficulty": "Beginner",
            "temperament": "Solitary",
            "lifespan": "3–5 years",
            "diet": "Pellets, frozen/live food",
        },
        "tags": ["freshwater", "beginner", "solitary", "colorful"],
        "demo_data": True,
    },
    {
        "id": "aq002",
        "name": "Neon Tetra",
        "category": "fish_aquarium",
        "price": "₹50–₹80 per fish (est.)",
        "price_num": 65,
        "rating": 4.6,
        "specs": {
            "tank_size": "Minimum 40 litres",
            "water_type": "Freshwater",
            "difficulty": "Beginner–Intermediate",
            "temperament": "Peaceful schooling",
            "lifespan": "5–10 years",
            "diet": "Micro pellets, flakes",
        },
        "tags": ["freshwater", "beginner", "schooling", "colorful"],
        "demo_data": True,
    },
    {
        "id": "aq003",
        "name": "Goldfish (Common / Fancy)",
        "category": "fish_aquarium",
        "price": "₹50–₹500 per fish (est.)",
        "price_num": 150,
        "rating": 4.2,
        "specs": {
            "tank_size": "Minimum 75 litres",
            "water_type": "Freshwater",
            "difficulty": "Beginner",
            "temperament": "Peaceful",
            "lifespan": "10–15 years",
            "diet": "Pellets, vegetables",
        },
        "tags": ["freshwater", "beginner", "popular"],
        "demo_data": True,
    },
    {
        "id": "aq004",
        "name": "Clownfish (Amphiprioninae)",
        "category": "fish_aquarium",
        "price": "₹500–₹2000 (est.)",
        "price_num": 1000,
        "rating": 4.7,
        "specs": {
            "tank_size": "Minimum 75 litres",
            "water_type": "Saltwater",
            "difficulty": "Intermediate",
            "temperament": "Semi-aggressive",
            "lifespan": "6–10 years",
            "diet": "Omnivore – pellets, frozen food",
        },
        "tags": ["saltwater", "intermediate", "colorful", "popular"],
        "demo_data": True,
    },
    {
        "id": "aq005",
        "name": "Aqueon 20 Gallon Aquarium Starter Kit",
        "category": "fish_aquarium",
        "price": "₹8,000–₹12,000 (est.)",
        "price_num": 10000,
        "rating": 4.1,
        "specs": {
            "volume": "75 litres (20 gallons)",
            "includes": "Filter, LED light, heater, hood",
            "type": "Glass",
            "suitable_for": "Freshwater beginners",
        },
        "tags": ["tank", "starter-kit", "freshwater", "beginner"],
        "demo_data": True,
    },
    {
        "id": "aq006",
        "name": "API Master Test Kit (Freshwater)",
        "category": "fish_aquarium",
        "price": "₹2,500–₹3,500 (est.)",
        "price_num": 3000,
        "rating": 4.8,
        "specs": {
            "tests": "pH, Ammonia, Nitrite, Nitrate",
            "tests_per_kit": "800+",
            "type": "Liquid reagent test",
        },
        "tags": ["water-testing", "maintenance", "essential"],
        "demo_data": True,
    },
]

DEMO_PET_SUPPLIES: List[Dict[str, Any]] = [
    {
        "id": "pet001",
        "name": "Royal Canin Maxi Adult Dog Food (4kg)",
        "category": "pet",
        "price": "₹2,200 (est.)",
        "price_num": 2200,
        "rating": 4.5,
        "specs": {
            "type": "Dry Dog Food",
            "weight": "4 kg",
            "breed_size": "Large breeds (26–44 kg)",
            "ingredients": "Chicken meal, rice, corn",
        },
        "tags": ["dog", "food", "large-breed", "dry"],
        "demo_data": True,
    },
    {
        "id": "pet002",
        "name": "Whiskas Tuna Pouch Cat Food (85g x 12)",
        "category": "pet",
        "price": "₹650 (est.)",
        "price_num": 650,
        "rating": 4.3,
        "specs": {
            "type": "Wet Cat Food",
            "weight": "12 x 85g",
            "flavour": "Tuna in Jelly",
        },
        "tags": ["cat", "food", "wet"],
        "demo_data": True,
    },
    {
        "id": "pet003",
        "name": "Pet Zone Dog Carrier Bag (Medium)",
        "category": "pet",
        "price": "₹1,800 (est.)",
        "price_num": 1800,
        "rating": 4.0,
        "specs": {
            "dimensions": "45 x 30 x 28 cm",
            "material": "Oxford fabric",
            "capacity": "Up to 6 kg pet",
            "features": "Mesh windows, shoulder strap",
        },
        "tags": ["dog", "cat", "carrier", "travel"],
        "demo_data": True,
    },
    {
        "id": "pet004",
        "name": "Pedigree Adult Dog Food Chicken & Vegetables (3kg)",
        "category": "pet",
        "price": "₹750 (est.)",
        "price_num": 750,
        "rating": 4.1,
        "specs": {
            "type": "Dry Dog Food",
            "weight": "3 kg",
            "flavour": "Chicken & Vegetables",
        },
        "tags": ["dog", "food", "budget", "dry"],
        "demo_data": True,
    },
    {
        "id": "pet005",
        "name": "Trixie Scratching Post for Cats (60cm)",
        "category": "pet",
        "price": "₹1,200 (est.)",
        "price_num": 1200,
        "rating": 4.2,
        "specs": {
            "height": "60 cm",
            "material": "Sisal, plush",
            "base": "Weighted",
        },
        "tags": ["cat", "scratching", "toy", "furniture"],
        "demo_data": True,
    },
    {
        "id": "pet006",
        "name": "Furminator Undercoat deShedding Tool for Large Dogs",
        "category": "pet",
        "price": "₹1,750 (est.)",
        "price_num": 1750,
        "rating": 4.8,
        "specs": {
            "type": "Grooming & Shedding Brush",
            "compatibility": "Golden Retriever, Labrador, GSD",
            "benefit": "Reduces loose hair shedding by up to 90%",
            "features": "Stainless steel edge, FURejector button",
        },
        "tags": ["dog", "grooming", "golden retriever", "labrador", "shedding"],
        "demo_data": True,
    },
    {
        "id": "pet007",
        "name": "KONG Classic Durable Rubber Dog Toy (Large)",
        "category": "pet",
        "price": "₹1,100 (est.)",
        "price_num": 1100,
        "rating": 4.7,
        "specs": {
            "type": "Chew & Enrichment Toy",
            "material": "Ultra-durable natural red rubber",
            "benefit": "Mental stimulation, prevents destructive chewing",
            "features": "Treat-stuffable chamber",
        },
        "tags": ["dog", "toy", "chew", "enrichment", "golden retriever", "labrador"],
        "demo_data": True,
    },
    {
        "id": "pet008",
        "name": "BarkButler Orthopedic Memory Foam Dog Bed (Large)",
        "category": "pet",
        "price": "₹3,200 (est.)",
        "price_num": 3200,
        "rating": 4.6,
        "specs": {
            "dimensions": "100 x 70 x 15 cm",
            "material": "High-density orthopedic memory foam",
            "benefit": "Joint and hip relief for large breeds",
            "cover": "Waterproof, machine-washable zip cover",
        },
        "tags": ["dog", "bed", "orthopedic", "large-breed"],
        "demo_data": True,
    },
    {
        "id": "pet009",
        "name": "Catit Hooded Cat Litter Box with Carbon Filter",
        "category": "pet",
        "price": "₹1,650 (est.)",
        "price_num": 1650,
        "rating": 4.5,
        "specs": {
            "type": "Hooded Litter Pan",
            "dimensions": "57 x 46 x 50 cm",
            "odor_control": "Integrated activated carbon filter",
            "features": "Easy-locking door, flap access",
        },
        "tags": ["cat", "litter", "hygiene", "indoor"],
        "demo_data": True,
    },
]

DEMO_RELATIONSHIP_RESOURCES: List[Dict[str, Any]] = [
    {
        "id": "rel001",
        "name": "Nonviolent Communication: A Language of Life (Marshall Rosenberg)",
        "category": "relationship",
        "price": "₹499 (est. paperback)",
        "price_num": 499,
        "rating": 4.8,
        "specs": {
            "type": "Communication Guide",
            "topic": "Conflict Resolution & Empathy",
            "format": "Paperback / Audiobook",
            "recommended_for": "Healing strained relationships",
        },
        "tags": ["communication", "conflict-resolution", "empathy", "relationships"],
        "demo_data": True,
    },
    {
        "id": "rel002",
        "name": "Difficult Conversations: How to Discuss What Matters Most",
        "category": "relationship",
        "price": "₹450 (est. paperback)",
        "price_num": 450,
        "rating": 4.7,
        "specs": {
            "type": "Handbook",
            "topic": "Harvard Negotiation Project Framework",
            "format": "Book",
            "recommended_for": "Navigating intense disagreements",
        },
        "tags": ["conversations", "friendship", "boundaries"],
        "demo_data": True,
    },
    {
        "id": "rel003",
        "name": "Attached: The New Science of Adult Attachment",
        "category": "relationship",
        "price": "₹399 (est. paperback)",
        "price_num": 399,
        "rating": 4.6,
        "specs": {
            "type": "Psychology Guide",
            "topic": "Attachment Styles & Dependency",
            "format": "Book",
            "recommended_for": "Understanding fear of abandonment and healthy boundaries",
        },
        "tags": ["attachment", "emotional-independence", "relationships"],
        "demo_data": True,
    },
]

DEMO_PC_COMPONENTS: List[Dict[str, Any]] = [
    {
        "id": "pc001",
        "name": "AMD Ryzen 7 7800X3D Desktop Processor",
        "category": "pc_components",
        "price": "₹38,499 (est.)",
        "price_num": 38499,
        "rating": 4.9,
        "specs": {"cores": "8 Cores / 16 Threads", "boost_clock": "Up to 5.0 GHz", "cache": "104MB 3D V-Cache", "socket": "AM5", "tdp": "120W"},
        "tags": ["cpu", "gaming", "high-performance", "am5"],
        "demo_data": True,
    },
    {
        "id": "pc002",
        "name": "NVIDIA GeForce RTX 4070 Ti Super 16GB",
        "category": "pc_components",
        "price": "₹79,999 (est.)",
        "price_num": 79999,
        "rating": 4.8,
        "specs": {"vram": "16GB GDDR6X", "bus": "256-bit", "architecture": "Ada Lovelace", "ray_tracing": "3rd Gen RT Cores", "dlss": "DLSS 3.5"},
        "tags": ["gpu", "gaming", "ai-ml", "4k"],
        "demo_data": True,
    },
    {
        "id": "pc003",
        "name": "Samsung 990 Pro 2TB NVMe PCIe 4.0 SSD",
        "category": "pc_components",
        "price": "₹16,499 (est.)",
        "price_num": 16499,
        "rating": 4.8,
        "specs": {"read_speed": "Up to 7,450 MB/s", "write_speed": "Up to 6,900 MB/s", "form_factor": "M.2 2280", "interface": "PCIe 4.0 x4"},
        "tags": ["storage", "fast", "gaming", "nvme"],
        "demo_data": True,
    },
    {
        "id": "pc004",
        "name": "Corsair Vengeance DDR5 32GB (2x16GB) 6000MHz CL30",
        "category": "pc_components",
        "price": "₹9,999 (est.)",
        "price_num": 9999,
        "rating": 4.7,
        "specs": {"capacity": "32GB (2x16GB)", "speed": "DDR5-6000", "latency": "CL30", "profile": "AMD EXPO & Intel XMP 3.0"},
        "tags": ["ram", "memory", "ddr5", "fast"],
        "demo_data": True,
    },
    {
        "id": "pc005",
        "name": "MSI MAG B650 Tomahawk WiFi Motherboard",
        "category": "pc_components",
        "price": "₹19,990 (est.)",
        "price_num": 19990,
        "rating": 4.6,
        "specs": {"socket": "AM5", "chipset": "AMD B650", "wifi": "Wi-Fi 6E + 2.5G LAN", "pcie": "PCIe 4.0", "vrm": "14+2+1 Power Stages"},
        "tags": ["motherboard", "am5", "wifi"],
        "demo_data": True,
    },
    {
        "id": "pc006",
        "name": "Corsair RM850x 850W 80 Plus Gold Modular PSU",
        "category": "pc_components",
        "price": "₹10,899 (est.)",
        "price_num": 10899,
        "rating": 4.8,
        "specs": {"wattage": "850W", "efficiency": "80 PLUS Gold", "modular": "Fully Modular", "fan": "135mm Magnetic Levitation", "warranty": "10 Years"},
        "tags": ["power-supply", "psu", "gold", "modular"],
        "demo_data": True,
    },
]

DEMO_EDUCATION: List[Dict[str, Any]] = [
    {
        "id": "edu001",
        "name": "Complete Python Pro Bootcamp (Dr. Angela Yu)",
        "category": "education",
        "price": "₹3,499 (est. lifetime access)",
        "price_num": 3499,
        "rating": 4.9,
        "specs": {"curriculum": "100 Days of Code (Beginner to Pro)", "projects": "100 Hands-on Projects", "skills": "Python, OOP, Web Scraping, Flask, Data", "format": "On-demand Video + Code Exercises"},
        "tags": ["python", "coding", "programming", "beginner", "bootcamp"],
        "demo_data": True,
    },
    {
        "id": "edu002",
        "name": "Harvard CS50: Introduction to Computer Science",
        "category": "education",
        "price": "Free (₹12,500 for Verified Certificate)",
        "price_num": 12500,
        "rating": 4.9,
        "specs": {"institution": "Harvard University", "level": "Introductory / Rigorous", "topics": "C, Python, SQL, Algorithms, Data Structures", "duration": "12 Weeks (Self-paced)"},
        "tags": ["computer-science", "algorithms", "harvard", "cs50"],
        "demo_data": True,
    },
    {
        "id": "edu003",
        "name": "Google IT Automation with Python Professional Certificate",
        "category": "education",
        "price": "₹14,999 / year (Coursera Plus)",
        "price_num": 14999,
        "rating": 4.8,
        "specs": {"provider": "Google", "courses": "6-course series", "topics": "Python, Git/GitHub, Troubleshooting, System Administration", "credential": "Shareable Industry Certificate"},
        "tags": ["google", "automation", "python", "career-certificate"],
        "demo_data": True,
    },
    {
        "id": "edu004",
        "name": "Meta Front-End Developer Professional Certificate",
        "category": "education",
        "price": "₹14,999 / year (Coursera Plus)",
        "price_num": 14999,
        "rating": 4.7,
        "specs": {"provider": "Meta", "courses": "9-course series", "skills": "HTML/CSS, JavaScript, React, UI/UX, Git", "portfolio": "Capstone Production Project"},
        "tags": ["web-development", "react", "frontend", "meta"],
        "demo_data": True,
    },
]

DEMO_CAREER: List[Dict[str, Any]] = [
    {
        "id": "car001",
        "name": "LinkedIn Premium Career Subscription (6 Months)",
        "category": "career",
        "price": "₹8,999 (est.)",
        "price_num": 8999,
        "rating": 4.5,
        "specs": {"features": "InMail messages to recruiters, who viewed profile, applicant insights, LinkedIn Learning", "duration": "6 Months"},
        "tags": ["career", "networking", "jobs", "linkedin"],
        "demo_data": True,
    },
    {
        "id": "car002",
        "name": "Executive Resume & Portfolio Professional Notion Template Suite",
        "category": "career",
        "price": "₹1,499 (est.)",
        "price_num": 1499,
        "rating": 4.8,
        "specs": {"formats": "ATS-friendly PDF, Notion Site, Figma Template", "extras": "Cover letter builder, 50+ impact verbs guide"},
        "tags": ["resume", "portfolio", "ats", "interview"],
        "demo_data": True,
    },
    {
        "id": "car003",
        "name": "Designing Your Life: Build a Well-Lived, Joyful Life (Bill Burnett)",
        "category": "career",
        "price": "₹699 (est. paperback)",
        "price_num": 699,
        "rating": 4.7,
        "specs": {"authors": "Stanford Design Program Leaders", "framework": "Design Thinking applied to Career & Life transitions"},
        "tags": ["career-change", "design-thinking", "self-help"],
        "demo_data": True,
    },
]

DEMO_TRAVEL: List[Dict[str, Any]] = [
    {
        "id": "trv001",
        "name": "American Tourister 68cm Polycarbonate Hardside Spinner Luggage",
        "category": "travel",
        "price": "₹5,499 (est.)",
        "price_num": 5499,
        "rating": 4.4,
        "specs": {"material": "Scratch-resistant Polycarbonate", "lock": "Recessed TSA Combination Lock", "wheels": "360-degree Double Wheels", "capacity": "68 cm / 72L"},
        "tags": ["luggage", "suitcase", "travel-gear"],
        "demo_data": True,
    },
    {
        "id": "trv002",
        "name": "Sony WH-1000XM4 Wireless Noise-Cancelling Headphones",
        "category": "travel",
        "price": "₹22,990 (est.)",
        "price_num": 22990,
        "rating": 4.8,
        "specs": {"noise_cancelling": "Industry-leading Dual Sensor ANC", "battery": "30 hrs with Fast Charge", "codec": "LDAC, AAC, SBC", "portability": "Foldable with Travel Case"},
        "tags": ["headphones", "anc", "travel", "audio"],
        "demo_data": True,
    },
    {
        "id": "trv003",
        "name": "Universal All-in-One Travel Adapter with 65W GaN Fast Charger",
        "category": "travel",
        "price": "₹2,499 (est.)",
        "price_num": 2499,
        "rating": 4.7,
        "specs": {"compatibility": "150+ Countries (US/UK/EU/AU)", "ports": "2x USB-C + 2x USB-A + AC Socket", "charging": "65W GaN Fast Charge", "safety": "Dual 8A Overload Fuse"},
        "tags": ["adapter", "charger", "travel-essentials"],
        "demo_data": True,
    },
    {
        "id": "trv004",
        "name": "Osprey Farpoint 40 Travel Carry-On Backpack",
        "category": "travel",
        "price": "₹14,500 (est.)",
        "price_num": 14500,
        "rating": 4.8,
        "specs": {"volume": "40L Carry-On Size", "suspension": "LightWire Frame + Breathable Mesh", "laptop_sleeve": "Lockable 16\" Padded Compartment", "weight": "1.44 kg"},
        "tags": ["backpack", "carry-on", "travel"],
        "demo_data": True,
    },
]

DEMO_HOME: List[Dict[str, Any]] = [
    {
        "id": "hm001",
        "name": "LG 8kg 5-Star Inverter AI Direct Drive Front Load Washing Machine",
        "category": "home",
        "price": "₹36,990 (est.)",
        "price_num": 36990,
        "rating": 4.5,
        "specs": {"capacity": "8 kg", "motor": "Inverter Direct Drive", "energy_rating": "5 Star", "features": "Steam Wash & 6 Motion DD", "warranty": "10 Years on Motor"},
        "tags": ["appliance", "washing-machine", "lg"],
        "demo_data": True,
    },
    {
        "id": "hm002",
        "name": "Samsung 253L 3-Star Inverter Frost-Free Double Door Refrigerator",
        "category": "home",
        "price": "₹25,990 (est.)",
        "price_num": 25990,
        "rating": 4.4,
        "specs": {"capacity": "253 Litres", "compressor": "Digital Inverter", "cooling": "All-around Cooling", "stabilizer": "Stabilizer-free Operation"},
        "tags": ["refrigerator", "fridge", "samsung"],
        "demo_data": True,
    },
    {
        "id": "hm003",
        "name": "Coway Airmega 150 True HEPA Air Purifier",
        "category": "home",
        "price": "₹12,990 (est.)",
        "price_num": 12990,
        "rating": 4.6,
        "specs": {"filter": "Green True HEPA (99.99% PM 0.1)", "coverage": "355 sq. ft.", "indicator": "Real-time Air Quality Lamp", "sound": "Quiet 22 dB Sleep Mode"},
        "tags": ["air-purifier", "health", "hepa"],
        "demo_data": True,
    },
]

DEMO_VEHICLE: List[Dict[str, Any]] = [
    {
        "id": "veh001",
        "name": "Ather 450X Gen 3 High-Performance Electric Scooter",
        "category": "vehicle",
        "price": "₹1,45,000 (est. on-road)",
        "price_num": 145000,
        "rating": 4.6,
        "specs": {"range": "150 km TrueRange", "top_speed": "90 km/h", "acceleration": "0-40 km/h in 3.3s", "display": "7\" Touchscreen with Google Maps", "battery": "3.7 kWh IP67"},
        "tags": ["ev", "electric-scooter", "commuter", "ather"],
        "demo_data": True,
    },
    {
        "id": "veh002",
        "name": "Royal Enfield Hunter 350 (Dapper Series)",
        "category": "vehicle",
        "price": "₹1,69,900 (est. on-road)",
        "price_num": 169900,
        "rating": 4.5,
        "specs": {"engine": "349cc J-Series Single Cylinder", "power": "20.2 bhp", "torque": "27 Nm @ 4000 rpm", "brakes": "Dual Channel ABS", "weight": "181 kg agile roadster"},
        "tags": ["motorcycle", "bike", "royal-enfield", "commuter"],
        "demo_data": True,
    },
]

DEMO_HEALTH: List[Dict[str, Any]] = [
    {
        "id": "hlth001",
        "name": "Electral WHO-Formula Electrolyte Oral Rehydration Sachets (Box of 30)",
        "category": "health",
        "price": "₹650 (est.)",
        "price_num": 650,
        "rating": 4.9,
        "specs": {"standard": "WHO-recommended Osmolarity Formula", "contents": "Sodium, Potassium, Chloride, Dextrose", "purpose": "Rapid Rehydration & Cramp Relief", "pack": "30 Sachets"},
        "tags": ["hydration", "ors", "electrolyte", "recovery"],
        "demo_data": True,
    },
    {
        "id": "hlth002",
        "name": "Omron HEM-7120 Fully Automatic Digital Blood Pressure Monitor",
        "category": "health",
        "price": "₹2,150 (est.)",
        "price_num": 2150,
        "rating": 4.6,
        "specs": {"measurement": "IntelliSense Upper Arm Cuff", "indicators": "Hypertension & Irregular Heartbeat", "display": "Large LCD Digital Display", "accuracy": "Clinically Validated"},
        "tags": ["blood-pressure", "omron", "medical-device"],
        "demo_data": True,
    },
]

ALL_PRODUCTS = (
    DEMO_LAPTOPS + DEMO_PHONES + DEMO_OFFICE_EQUIPMENT + DEMO_FISH_AQUARIUM +
    DEMO_PET_SUPPLIES + DEMO_RELATIONSHIP_RESOURCES + DEMO_PC_COMPONENTS +
    DEMO_EDUCATION + DEMO_CAREER + DEMO_TRAVEL + DEMO_HOME + DEMO_VEHICLE + DEMO_HEALTH
)

CATEGORY_PRODUCT_MAP = {
    "laptop": DEMO_LAPTOPS,
    "smartphone": DEMO_PHONES,
    "phone": DEMO_PHONES,
    "pc_components": DEMO_PC_COMPONENTS,
    "desktop": DEMO_PC_COMPONENTS,
    "education": DEMO_EDUCATION,
    "career": DEMO_CAREER,
    "travel": DEMO_TRAVEL,
    "home": DEMO_HOME,
    "vehicle": DEMO_VEHICLE,
    "health": DEMO_HEALTH,
    "office_equipment": DEMO_OFFICE_EQUIPMENT,
    "fish_aquarium": DEMO_FISH_AQUARIUM,
    "pet": DEMO_PET_SUPPLIES,
    "company_bulk": DEMO_LAPTOPS + DEMO_OFFICE_EQUIPMENT,
    "relationship": DEMO_RELATIONSHIP_RESOURCES,
    "personal": DEMO_RELATIONSHIP_RESOURCES,
    "product_purchase": ALL_PRODUCTS,
}


def get_products_for_category(category: str, budget: Optional[Any] = None, quantity: Any = 1) -> List[Dict[str, Any]]:
    """Return filtered demo products for a category."""
    category = category.lower().strip()
    products = CATEGORY_PRODUCT_MAP.get(category, [])
    if not products:
        # Try partial match
        for key, prods in CATEGORY_PRODUCT_MAP.items():
            if key in category or category in key:
                products = prods
                break

    try:
        qty = int(quantity) if quantity is not None else 1
    except (ValueError, TypeError):
        qty = 1

    try:
        b_val = float(budget) if budget is not None else None
    except (ValueError, TypeError):
        b_val = None

    if b_val and b_val > 0 and products:
        unit_budget = b_val / max(qty, 1)
        products = [p for p in products if p.get("price_num", 0) <= unit_budget * 1.2]

    return products
